name: main
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create dotenv files
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "${{ secrets.ENV_FILE_1 }}" > feed-scraper/.env
          echo "${{ secrets.ENV_FILE_2 }}" > innonews/.env
      - name: Start Docker daemon
        run: |
          sudo systemctl start docker
      - name: Build and Run Docker containers
        run: |
          docker-compose up -d
      - name: Run tests
        run: |
          docker-compose exec -T producer python -m pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pre-commit
        run: |
          python -m pip install pre-commit
      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files --show-diff-on-failure
